services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: api_example
      MYSQL_USER: user347
      MYSQL_PASSWORD: pass347
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: user347
      DB_USERNAME_PASSWORD: pass347
      DB_NAME: api_example
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql-data: 